[package]
name = "belt"
version = "0.1.0"
authors = ["= <hjalte.nannestad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fumarole = { git = "https://github.com/changecaps/gui", branch = "develop" }